feat: single step sign in
lenstube-xyz/lenstube pull request #227
Opened 2022-10-20 15:13 UTC by benbaessler

## Description

Closes [#207](https://github.com/lenstube-xyz/lenstube/issues/207)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Minor changes in old functionality

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2022-12-09 15:52 UTC, sasicodes commented
@benbaessler can you please resolve the conflicts 🙇🏻?

2022-12-09 15:53 UTC, sasicodes commented
@benbaessler We also moved to monorepo structure!

2022-12-11 00:12 UTC, benbaessler commented
@sasicodes applied the repo updates to the code, everything should be working now. 🙂

2022-12-11 13:16 UTC, sasicodes commented
@benbaessler 

After successful login, disconnect the wallet directly in Metamask. You will see a Sign in failed error toast.

2022-12-12 23:02 UTC, benbaessler commented
> 

The problem is that the `useEffect` hook is being triggered before the variables update on disconnect.
Not sure if this would be in line with best practices, but this is a potential solution: 
```
useEffect(() => {
  if (
    connector?.id &&
    isConnected &&
    chain?.id === POLYGON_CHAIN_ID &&
    !selectedChannel &&
    !selectedChannelId
  ) {
    handleSign()
  }
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [isConnected])
```
Should I implement this solution @sasicodes ?

2022-12-13 05:05 UTC, sasicodes commented
yes, we can try it.

2022-12-14 14:55 UTC, benbaessler commented
done, sorry for the delay. @sasicodes

2022-12-14 15:30 UTC, sasicodes requested changes

2022-12-14 15:30 UTC, sasicodes commented on apps/web/src/components/Common/Auth/Login.tsx
> +      connector?.id &&
shall we have this all in a const and use it if condition?

2023-01-13 11:39 UTC, sasicodes approved these changes

2023-01-13 11:41 UTC, merged