remove non-null assertion operator
lenstube-xyz/lenstube pull request #398
Opened 2022-11-23 12:13 UTC by zt4ff

## Description

Closes #368 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

2022-12-02 13:46 UTC, sasicodes commented
@zt4ff have added a comment

2022-12-06 03:07 UTC, sasicodes requested changes

2022-12-06 23:00 UTC, zt4ff commented on packages/utils/functions/uploadToIPFS.ts
> +      const progress = ((e.loaded / e.total) * 100) | 0
@sasicodes 
It is a TypeScript notation that tells the compiler that `.loaded` cannot be `null` or `undefined`

2022-12-07 07:32 UTC, sasicodes requested changes

2022-12-07 07:32 UTC, sasicodes commented on packages/utils/functions/uploadToIPFS.ts
> +      const progress = ((e.loaded / e.total) * 100) | 0
can we use a separate variable for the loaded and total with nullish check?

loaded = e.loaded ?? 0
total = e.total ?? 0

2022-12-07 07:36 UTC, sasicodes commented
@zt4ff  have added comment 🙇🏻 
![image](https://user-images.githubusercontent.com/29498872/206116954-9781b0a6-461d-4d31-af6a-eb2b0d670abc.png)

2022-12-11 07:36 UTC, sasicodes commented
@zt4ff https://github.com/lenstube-xyz/lenstube/pull/398#issuecomment-1340520777

2023-01-09 07:39 UTC, sasicodes commented
Fixed ✅

2023-01-09 07:39 UTC, closed without merging