Set nft as profile
lenstube-xyz/lenstube pull request #519
Opened 2023-01-07 16:42 UTC by RamK777-stack

## Description
Ability to set NFT as Channel Avatar

Closes #22

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2023-01-08 06:16 UTC, sasicodes commented on apps/web/package.json
> +    "react-image-crop": "^10.0.9"
```suggestion
    "react-image-crop": "^10.0.9",
```

2023-01-08 06:26 UTC, sasicodes requested changes

2023-01-08 06:26 UTC, sasicodes commented on apps/web/src/components/Settings/CropImageModal.tsx
> +            src={imageSrc}
this needs to be addressed 🙇🏻

2023-01-08 06:26 UTC, sasicodes commented on apps/web/src/components/Settings/CropImageModal.tsx
> +          ></img>
can be self-closing tag <img/>

2023-01-08 06:26 UTC, sasicodes commented on packages/utils/functions/sanitizeIpfsUrl.ts
> +    .replace('https://ipfs.io/ipfs/', gateway)
if we are adding `/` here, we need to remove it in constants.ts

2023-01-08 06:26 UTC, sasicodes commented on apps/web/src/components/Settings/CropImageModal.tsx
> +      console.log('crop the image')
add logger!

2023-01-08 06:26 UTC, sasicodes commented on apps/web/src/components/Settings/ChannelPicture.tsx
> +
```suggestion
```

2023-01-08 13:05 UTC, sasicodes commented
<img width="148" alt="image" src="https://user-images.githubusercontent.com/29498872/211197542-8a40e1a1-bc22-4889-be99-613826d98b3f.png">

can we add some margin to right and bottom @RamK777-stack

2023-01-08 13:07 UTC, RamK777-stack commented on apps/web/src/components/Settings/CropImageModal.tsx
> +          ></img>
Resolved

2023-01-08 13:11 UTC, sasicodes requested changes

2023-01-08 13:11 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +                        <img
add fixed height for images.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/29498872/211197638-4255fd70-a3a8-4c70-8443-836dedacca92.png">

2023-01-09 16:36 UTC, sasicodes requested changes

2023-01-09 16:36 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +    chainId: Number
```suggestion
    chainId: number
```

2023-01-09 16:36 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +              {loading && <TimelineShimmer />}
move the shimmer above the map nfts and timeline shimmer looks good for a square image grid. we can use just middle spinner if needed

2023-01-09 16:36 UTC, sasicodes commented on apps/web/src/components/Settings/CropImageModal.tsx
> +type Props = {
Move type declaration below all imports

2023-01-09 16:36 UTC, sasicodes commented on apps/web/src/components/Settings/CropImageModal.tsx
> +        const file = new File([blob as Blob], 'fileName.jpg', {
```suggestion
        const file = new File([blob as Blob], 'nft.jpg', {
```

2023-01-09 16:39 UTC, sasicodes requested changes

2023-01-09 16:39 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +                          className="rounded-xl cursor-pointer h-20 w-36"
we can have 1:1 square image

2023-01-09 16:39 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +                  <div className="grid grid-cols-3 gap-5">
check responsiveness in mobile view

2023-01-12 15:14 UTC, sasicodes requested changes

2023-01-12 15:14 UTC, sasicodes commented on apps/web/src/components/Settings/CropImageModal.tsx
> +          className="rounded-lg"
```suggestion
```

2023-01-15 15:45 UTC, sasicodes requested changes

2023-01-15 15:45 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +        <Tab.Group>
can we make this tabgroup a separate component?

2023-01-15 15:45 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +                    : 'border-transparent opacity-50 hover:bg-indigo-500/[0.12] rounded-tl-lg rounded-tr-lg'
```suggestion
                    : 'border-transparent opacity-50 hover:bg-indigo-200 dark:hover:bg-indigo-800 rounded-tl-lg rounded-tr-lg'
```

2023-01-15 15:45 UTC, sasicodes commented on apps/web/src/components/Settings/ChoosePicture.tsx
> +                    : 'border-transparent opacity-50 hover:bg-indigo-500/[0.12] rounded-tl-lg rounded-tr-lg'
```suggestion
                    : 'border-transparent opacity-50 hover:bg-indigo-200 dark:hover:bg-indigo-800 rounded-tl-lg rounded-tr-lg'
```

2023-01-15 15:45 UTC, sasicodes commented on apps/web/src/components/Settings/CropImagePreview.tsx
> +          className="h-[50vh] object-fit"
this `h-50vh` causes stretch.
![image](https://user-images.githubusercontent.com/29498872/212550999-e714817b-4f64-4056-9d39-d4d35a62c185.png)

2023-01-20 05:22 UTC, sasicodes requested changes

2023-01-20 05:22 UTC, sasicodes commented on apps/web/src/components/Settings/ChannelPicture.tsx
> +  const [showCropImagePreview, setShowCropImagePreview] = useState(false)
do we need this state here? closing profile modal closes everything right?

2023-01-20 05:23 UTC, sasicodes requested changes

2023-01-20 05:23 UTC, sasicodes commented on apps/web/src/components/Settings/ChannelPicture.tsx
> +  const [showProfileModal, setProfileModal] = useState(false)
```suggestion
  const [showProfileModal, setShowProfileModal] = useState(false)
```

2023-01-20 06:50 UTC, sasicodes commented
@RamK777-stack everything looks good! We need the third point to be done to differentiate nft pfp.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/29498872/213634931-708f27e9-b53d-4955-80c1-c4243ec151e1.png">

2023-01-20 09:58 UTC, sasicodes commented
Bounty $100 - https://polygonscan.com/tx/0x192aa326a5ca221971aafd94781f819afefa034b93b5aac5b88426fcaf448df8

2023-02-12 13:59 UTC, sasicodes commented
@RamK777-stack Any updates on this ser 🙇🏻 ?

2023-02-19 22:37 UTC, abhiram11 commented
Hi, I will try to work on this, give me some time to research and if I can do some workaround, I will request you to assign me this!

2023-02-20 07:35 UTC, sasicodes commented
> Hi, I will try to work on this, give me some time to research and if I can do some workaround, I will request you to assign me this!

I think @RamK777-stack is yet to finish. 🙇🏻

2023-02-20 09:42 UTC, abhiram11 commented
> > Hi, I will try to work on this, give me some time to research and if I can do some workaround, I will request you to assign me this!
> 
> I think @RamK777-stack is yet to finish. 🙇🏻

Sure thing! Not in any rush, happy to assist!

2023-02-20 16:13 UTC, sasicodes commented
> > > Hi, I will try to work on this, give me some time to research and if I can do some workaround, I will request you to assign me this!
> > 
> > 
> > I think @RamK777-stack is yet to finish. 🙇🏻
> 
> Sure thing! Not in any rush, happy to assist!

Join our discord to find the `builder` channel, where we can discuss on potential features and issues.

2023-03-05 06:21 UTC, sasicodes commented
@RamK777-stack Please resolve conflicts 🙇🏻

2023-03-05 12:45 UTC, RamK777-stack commented
Okay I am working on it

On Sun, Mar 5, 2023, 11:51 Sasi ***@***.***> wrote:

> @RamK777-stack <https://github.com/RamK777-stack> Please resolve
> conflicts 🙇🏻
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lenstube-xyz/lenstube/pull/519#issuecomment-1455002361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPWSVDGW2RMYAANBIBRH5TW2QWF5ANCNFSM6AAAAAATUBHUQE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-16 12:07 UTC, sasicodes commented
We can reopen once done.

2023-05-16 12:07 UTC, closed without merging